### ISSUE TITLE
Can't start Strapi

### ISSUE THREAD

**Issue by tuannguyenminh2086** [strapi/strapi-starter-next-blog#10]
`...../s/backend> yarn develop
yarn run v1.22.4
$ strapi develop
/bin/sh: npm: command not found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Please help me?

**Comment by Mcastres** [comment]
Sorry this command is not available anymore. Please run your backend and frontend seprarately
