### ISSUE TITLE
Can´t start NEXT SERVER 

### ISSUE THREAD

**Issue by zoucer** [strapi/strapi-starter-next-blog#11]
Unhandled Runtime Error
TypeError: Only absolute URLs are supported

lib\api.js (2:20) @ fetchAPI

  1 | async function fetchAPI(query, { variables } = {}) {
> 2 |   const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/graphql`, {
    |                                ^
  3 |     method: 'POST',
  4 |     headers: {
  5 |       'Content-Type': 'application/json',

**Comment by Hyun2** [comment]
Did you solve it? I created a .env.local file, but I got the same error.
(My OS is windows 10)

**Comment by Hyun2** [comment]
sovled, after I updated next verison to 9.4
