### ISSUE TITLE
no dependency for Apollo in FE package.json

### ISSUE THREAD

**Issue by juicecultus** [strapi/strapi-starter-next-blog#14]
Hi guys,

You mention this project is the result of this tutorial (https://strapi.io/blog/build-a-blog-with-next-react-js-strapi-and-apollo) but looking at the front end package.json I cannot see any dependency for Apollo?! 

Can you clarify... as I see you use queries throughout to access the /graphQL endpoint in Strapi back end.

**Comment by Mcastres** [comment]
Sorry, I should update the title since it's no longer using Apollo! Thanks for that @juicecultus :)

**Comment by SalahAdDin** [comment]
@Mcastres I realized it too, why are not you using Apollo anymore?
