### ISSUE TITLE
Strapi Starter Next Blog doen't work on Vercel

### ISSUE THREAD

**Issue by ryota-murakami** [strapi/strapi-starter-next-blog#21]
At the `Deploy the frontend` section of [Strapi Starter Next Blog](https://strapi.io/blog/strapi-starter-next-js-blog) I stuck with **Invalid now.json file Provided** error prompt like bellow image.

<img width="1208" alt="Screen Shot 2020-09-15 at 15 17 22" src="https://user-images.githubusercontent.com/5501268/93172850-982c8200-f766-11ea-8877-17c4040e66f3.png">

Besides that the article instruct `now` command but `now` is deprecated at the time, `vercel` recommended.

**Comment by remi2j** [comment]
This bug comes from an error in the now.json file. This starter no longer has that file, so I'm closing this issue.

Bug you can fix this for your own project by applying [this fix](https://github.com/strapi/strapi-starter-next-blog/pull/18/files#diff-96c813af76efae3c872399365c060e54)

**Comment by ryota-murakami** [comment]
@remi2j Ok, thanks!
