### ISSUE TITLE
Strapi Multiple Image for Article

### ISSUE THREAD

**Issue by mumrucan** [strapi/strapi-starter-next-blog#26]
When I changed the strapi image type to multiple .. there is an error. 
How can I add the image slider(maybe 3 photos) to the article page?
Thank you.

**Comment by remidej** [comment]
There is an error because this starter expects a single picture is expecting an object, and you're passing it an array of objects. The current code looks like this:

```js
<div className="uk-card-media-top">
  <Image image={article.image} />
</div>
```

To display several images, you would need something like this:

```js
<div className="uk-card-media-top">
  {article.image.map(image => (
    <Image image={image} />
   ))}
  <Image image={article.image} />
</div>
```
