### ISSUE TITLE
No app.json located in the repo URL provided.

### ISSUE THREAD

**Issue by hbakhtiyor** [strapi/strapi-starter-next-blog#28]
in heroku

from this instruction, https://strapi.io/blog/strapi-online-meetup-4-recap

**Comment by remidej** [comment]
Hello! We have removed all files specific to Heroku in our starters, so that they can be used with any cloud provider.

To deploy a Strapi app to Heroku, follow this guide instead: https://strapi.io/documentation/developer-docs/latest/deployment/heroku.html#heroku

**Comment by jdahdah** [comment]
@remidej That's a dead link.
