### ISSUE TITLE
Missing API env for FE

### ISSUE THREAD

**Issue by jeanbauer** [strapi/strapi-starter-next-blog#7]
Hey! I saw that you removed .env.example from the FE source code but I don't think it is bad to let it there. For example we could use the new `NEXT_PUBLIC_` prefix.

What do you think?
 
https://nextjs.org/blog/next-9-4#new-environment-variables-support

I can open a PR if you agree. Have a good day!

**Comment by Mcastres** [comment]
You're right @jeanbauer ! Feel free to open one :)
